services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: msts_gjs_store
      POSTGRES_USER: msts_user
      POSTGRES_PASSWORD: msts_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
