# Generated by Django 5.2.15 on 2026-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_drop_legacy_otp_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('reset', 'Password Reset'), ('profile_edit', 'Profile Edit')], default='login', max_length=20),
        ),
    ]
