# Generated by Django 5.2.15 on 2026-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_bypass_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_estimated_end',
            field=models.CharField(blank=True, default='Expected to return shortly', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_message',
            field=models.TextField(default="We are currently upgrading server systems and performing essential depot maintenance. We'll be back online shortly!"),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_title',
            field=models.CharField(default='System Under Scheduled Maintenance', max_length=200),
        ),
    ]
