# Generated by Django 5.2.15 on 2026-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_sitesetting_maintenance_bypass_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='desktop_app_download_url',
            field=models.URLField(blank=True, default='https://github.com/gjs24/GJS-STORE4MSTS/releases', help_text='Direct link or host URL (e.g. Google Drive, GitHub Releases) for downloading Windows desktop installer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='desktop_app_version',
            field=models.CharField(blank=True, default='1.0.0', help_text='Current desktop app release version string', max_length=50),
        ),
    ]
