# Generated by Django 5.2.15 on 2026-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_sitesetting_desktop_app_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='desktop_app_enabled',
            field=models.BooleanField(default=False, help_text='Toggle public visibility of desktop app download links and page'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='desktop_app_download_url',
            field=models.URLField(blank=True, default='https://github.com/gjs24/msts-gjs-desktop-releases/releases/download/v1.0.0/MSTS-GJS.Production.Store.Setup.1.0.0.exe', help_text='Direct link or host URL (e.g. Google Drive, GitHub Releases) for downloading Windows desktop installer'),
        ),
    ]
