# Generated by Django 5.2.15 on 2026-09-09 16:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_sitesetting_desktop_app_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='early_access_badge',
            field=models.CharField(blank=True, default='VIP Early Access', max_length=60),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_has_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_has_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_required_assets',
            field=models.ManyToManyField(blank=True, related_name='early_access_unlocked_assets', to='store.asset'),
        ),
    ]
