# Generated by Django 5.2.15 on 2026-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_asset_early_access_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='early_access_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='early_access_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
