# Generated by Django 5.2.15 on 2026-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_asset_early_access_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='festival_announcement_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_badge',
            field=models.CharField(default='1st Year Anniversary', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_banner_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_button_text',
            field=models.CharField(default='Explore Anniversary Specials', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_button_url',
            field=models.CharField(default='/assets', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_effect',
            field=models.CharField(choices=[('confetti', 'Confetti Streamers'), ('sparkles', 'Golden Sparkles'), ('snow', 'Winter Snowfall'), ('fireworks', 'Celebratory Fireworks'), ('diyas', 'Glowing Festive Diyas'), ('none', 'No Effects (Banner Only)')], default='confetti', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_popup_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_subtitle',
            field=models.TextField(default='Thank you to our Indian Railways simulation community for 1 year of amazing support! Explore exclusive anniversary addons & special offers.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_theme_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_theme_type',
            field=models.CharField(choices=[('ANNIVERSARY', '1st Year Anniversary'), ('DIWALI', 'Diwali Festival of Lights'), ('PONGAL', 'Pongal / Sankranti Harvest'), ('CHRISTMAS', 'Christmas Holiday Season'), ('NEW_YEAR', 'New Year Celebration'), ('INDEPENDENCE_DAY', 'Independence / Republic Day'), ('CUSTOM', 'Custom Celebration')], default='ANNIVERSARY', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='festival_title',
            field=models.CharField(default='🎉 Celebrating 1 Year of MSTS-GJS Production Store!', max_length=160),
        ),
    ]
