# Generated by Django 5.2.15 on 2026-09-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_sitesetting_festival_announcement_bar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='festival_effect',
            field=models.CharField(choices=[('skyshots', 'Sky Shots & Crackers'), ('fireworks', 'Celebratory Fireworks & Crackers'), ('confetti', 'Confetti Streamers'), ('sparkles', 'Golden Sparkles'), ('snow', 'Winter Snowfall'), ('diyas', 'Glowing Festive Diyas'), ('none', 'No Effects (Banner Only)')], default='confetti', max_length=40),
        ),
    ]
