# Generated by Django 5.2.15 on 2026-09-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_sitesetting_festival_effect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_all_access_free', models.BooleanField(default=False, help_text='When true, this user can download any product for free like normal.')),
                ('admin_note', models.CharField(blank=True, default='', help_text='Internal reason or friendship note (visible to admins only).', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date. Null means permanent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_assets', models.ManyToManyField(blank=True, help_text='Specific assets granted for free if all-access is false.', related_name='special_access_users', to='store.asset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User special access',
                'verbose_name_plural': 'User special accesses',
            },
        ),
    ]
