# Generated by Django 5.2.15 on 2026-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_order_admin_notes_order_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='prebooking_badge',
            field=models.CharField(blank=True, default='PRE-BOOKING OPEN', max_length=60),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_download_unlock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_downloads_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_message',
            field=models.TextField(blank=True, default='Pre-book your copy now to lock in exclusive launch pricing and guarantee day-one access!'),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_slots',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
