from decimal import Decimal
from django.db import migrations

def seed_templates(apps, schema_editor):
    BoardTemplate = apps.get_model("store", "BoardTemplate")

    templates_data = [
        {
            "id": "amrit-bharat-led-1024",
            "name": "Amrit Bharat Express LED Destination Board",
            "category": "LED_MATRIX",
            "description": "Universal 1024x1024 LED destination matrix texture sheet for Amrit Bharat non-AC push-pull coaches. Features dual-line bilingual display, train number, and glowing amber LED diodes.",
            "base_width": 1024,
            "base_height": 1024,
            "is_paid": False,
            "price": Decimal("0.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_number",
                    "label": "Train Number",
                    "default_text": "15557",
                    "x": 40,
                    "y": 70,
                    "width": 210,
                    "height": 75,
                    "font": "VT323",
                    "font_size": 52,
                    "color": "#FFAA00",
                    "glow_color": "#FF7700",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "train_name_hi",
                    "label": "Train Name (Hindi)",
                    "default_text": "अमृत भारत एक्सप्रेस",
                    "x": 270,
                    "y": 55,
                    "width": 690,
                    "height": 45,
                    "font": "Noto Sans Devanagari",
                    "font_size": 30,
                    "color": "#FFAA00",
                    "glow_color": "#FF7700",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "train_name_en",
                    "label": "Train Name (English)",
                    "default_text": "AMRIT BHARAT EXPRESS",
                    "x": 270,
                    "y": 105,
                    "width": 690,
                    "height": 45,
                    "font": "VT323",
                    "font_size": 36,
                    "color": "#FFAA00",
                    "glow_color": "#FF7700",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "route_text",
                    "label": "Origin - Destination",
                    "default_text": "DBG ⇌ ANVT",
                    "x": 270,
                    "y": 160,
                    "width": 690,
                    "height": 38,
                    "font": "VT323",
                    "font_size": 30,
                    "color": "#FFAA00",
                    "glow_color": "#FF7700",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "coach_code",
                    "label": "Coach Indicator",
                    "default_text": "GS-1",
                    "x": 40,
                    "y": 160,
                    "width": 210,
                    "height": 38,
                    "font": "VT323",
                    "font_size": 30,
                    "color": "#39FF14",
                    "glow_color": "#00FF00",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
            ],
            "fixed_graphics": [
                {"type": "border", "x": 20, "y": 30, "width": 984, "height": 185, "color": "#1C1C1E", "border_width": 4},
                {"type": "separator", "x": 255, "y": 45, "x2": 255, "y2": 200, "color": "#2C2C2E"},
            ],
        },
        {
            "id": "vande-bharat-side-led-1024",
            "name": "Vande Bharat Express LED Side Panel Board",
            "category": "LED_MATRIX",
            "description": "Sleek aerodynamic trainside LED matrix display for Vande Bharat Express (Train 18) rakes. Amber glowing matrix with route marquee.",
            "base_width": 1024,
            "base_height": 1024,
            "is_paid": True,
            "price": Decimal("49.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_number",
                    "label": "Train Number",
                    "default_text": "20607",
                    "x": 60,
                    "y": 65,
                    "width": 200,
                    "height": 65,
                    "font": "VT323",
                    "font_size": 48,
                    "color": "#FF9900",
                    "glow_color": "#FF6600",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "train_name_en",
                    "label": "Train Name",
                    "default_text": "VANDE BHARAT EXP",
                    "x": 280,
                    "y": 65,
                    "width": 680,
                    "height": 65,
                    "font": "VT323",
                    "font_size": 42,
                    "color": "#FF9900",
                    "glow_color": "#FF6600",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "destination_text",
                    "label": "Destination",
                    "default_text": "MYS ⇌ MAS",
                    "x": 280,
                    "y": 145,
                    "width": 680,
                    "height": 50,
                    "font": "VT323",
                    "font_size": 34,
                    "color": "#FF9900",
                    "glow_color": "#FF6600",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
                {
                    "id": "car_id",
                    "label": "Car ID",
                    "default_text": "C-4",
                    "x": 60,
                    "y": 145,
                    "width": 200,
                    "height": 50,
                    "font": "VT323",
                    "font_size": 34,
                    "color": "#00E5FF",
                    "glow_color": "#00B0FF",
                    "dot_pitch": 4,
                    "matrix_mode": True,
                },
            ],
            "fixed_graphics": [
                {"type": "border", "x": 30, "y": 35, "width": 964, "height": 180, "color": "#0F172A", "border_width": 3},
            ],
        },
        {
            "id": "lhb-traditional-board-1024",
            "name": "LHB Superfast Acrylic / Metal Name Board",
            "category": "ACRYLIC_METAL",
            "description": "High-resolution 1024x1024 traditional Indian Railways acrylic destination board texture sheet with stainless steel border, bolts, and IR emblem.",
            "base_width": 1024,
            "base_height": 1024,
            "is_paid": False,
            "price": Decimal("0.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_number",
                    "label": "Train Number",
                    "default_text": "12637",
                    "x": 50,
                    "y": 75,
                    "width": 200,
                    "height": 60,
                    "font": "Arial Black",
                    "font_size": 42,
                    "color": "#FFFF00",
                    "glow_color": "transparent",
                    "dot_pitch": 0,
                    "matrix_mode": False,
                },
                {
                    "id": "train_name_hi",
                    "label": "Train Name (Hindi)",
                    "default_text": "पाण्डियन सुपरफास्ट एक्सप्रेस",
                    "x": 260,
                    "y": 60,
                    "width": 700,
                    "height": 50,
                    "font": "Noto Sans Devanagari",
                    "font_size": 34,
                    "color": "#FFFFFF",
                    "glow_color": "transparent",
                    "dot_pitch": 0,
                    "matrix_mode": False,
                },
                {
                    "id": "train_name_en",
                    "label": "Train Name (English)",
                    "default_text": "PANDIAN SUPERFAST EXPRESS",
                    "x": 260,
                    "y": 115,
                    "width": 700,
                    "height": 45,
                    "font": "Arial Black",
                    "font_size": 36,
                    "color": "#FFFFFF",
                    "glow_color": "transparent",
                    "dot_pitch": 0,
                    "matrix_mode": False,
                },
                {
                    "id": "via_stations",
                    "label": "Via Stations",
                    "default_text": "CHENGALPATTU • VILLUPURAM • TIRUCHCHIRAPPALLI • DINDIGUL",
                    "x": 60,
                    "y": 170,
                    "width": 900,
                    "height": 35,
                    "font": "Arial",
                    "font_size": 22,
                    "color": "#FFFF00",
                    "glow_color": "transparent",
                    "dot_pitch": 0,
                    "matrix_mode": False,
                },
                {
                    "id": "zone",
                    "label": "Railway Zone",
                    "default_text": "SOUTHERN RAILWAY",
                    "x": 50,
                    "y": 215,
                    "width": 300,
                    "height": 30,
                    "font": "Arial",
                    "font_size": 20,
                    "color": "#00FF66",
                    "glow_color": "transparent",
                    "dot_pitch": 0,
                    "matrix_mode": False,
                },
            ],
            "fixed_graphics": [
                {"type": "border", "x": 25, "y": 30, "width": 974, "height": 225, "color": "#B91C1C", "border_width": 6},
            ],
        },
        {
            "id": "wapp7-loco-led-1024",
            "name": "WAP-7 / WAP-5 Locomotive Headcode LED Matrix",
            "category": "LOCO_HEADCODE",
            "description": "Front locomotive cab destination headcode LED matrix for Indian Railways electric locomotives (WAP-7, WAP-5, WAG-9). High contrast bright amber diodes.",
            "base_width": 1024,
            "base_height": 1024,
            "is_paid": True,
            "price": Decimal("29.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_number",
                    "label": "Train Number",
                    "default_text": "12638",
                    "x": 80,
                    "y": 80,
                    "width": 280,
                    "height": 90,
                    "font": "VT323",
                    "font_size": 64,
                    "color": "#FFAA00",
                    "glow_color": "#FF7700",
                    "dot_pitch": 5,
                    "matrix_mode": True,
                },
                {
                    "id": "dest_code",
                    "label": "Destination Station",
                    "default_text": "MDU -> MS",
                    "x": 400,
                    "y": 80,
                    "width": 540,
                    "height": 90,
                    "font": "VT323",
                    "font_size": 60,
                    "color": "#FFAA00",
                    "glow_color": "#FF7700",
                    "dot_pitch": 5,
                    "matrix_mode": True,
                },
            ],
            "fixed_graphics": [
                {"type": "border", "x": 40, "y": 40, "width": 944, "height": 160, "color": "#0B0F19", "border_width": 5},
            ],
        },
    ]

    for item in templates_data:
        BoardTemplate.objects.update_or_create(id=item["id"], defaults=item)


def unseed_templates(apps, schema_editor):
    BoardTemplate = apps.get_model("store", "BoardTemplate")
    BoardTemplate.objects.filter(id__in=[
        "amrit-bharat-led-1024",
        "vande-bharat-side-led-1024",
        "lhb-traditional-board-1024",
        "wapp7-loco-led-1024"
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0036_boardtemplate_userboardunlock_usercustomboard_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_templates, unseed_templates),
    ]

