from decimal import Decimal
from django.db import migrations

def seed_gjs_nm_editor_templates(apps, schema_editor):
    BoardTemplate = apps.get_model("store", "BoardTemplate")

    templates_data = [
        {
            "id": "amrit-bharat-led-1024",
            "name": "Amrit Bharat LED 1024×1024 Texture Sheet",
            "category": "LED Texture Sheet",
            "description": "Authentic 1024×1024 Train Simulator UV texture sheet with glowing amber LED destination displays for Amrit Bharat Express.",
            "base_width": 1024,
            "base_height": 1024,
            "background_image_url": "/textures/amrit_bharat_led_sheet.png",
            "is_paid": False,
            "price": Decimal("0.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_no_up",
                    "label": "Train Number (Up)",
                    "defaultValue": "13433",
                    "placeholder": "13433",
                    "x": 18,
                    "y": 9,
                    "width": 20,
                    "height": 7,
                    "fontFamily": "'VT323', 'DotGothic16', monospace",
                    "fontSize": 52,
                    "fontWeight": 700,
                    "color": "#ff9f1c",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 4,
                    "ledGlow": True,
                    "glowColor": "#ff6200",
                    "glowRadius": 10,
                    "isDotMatrix": True,
                },
                {
                    "id": "train_no_dn",
                    "label": "Train Number (Down)",
                    "defaultValue": "13434",
                    "placeholder": "13434",
                    "x": 18,
                    "y": 15,
                    "width": 20,
                    "height": 7,
                    "fontFamily": "'VT323', 'DotGothic16', monospace",
                    "fontSize": 52,
                    "fontWeight": 700,
                    "color": "#ff9f1c",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 4,
                    "ledGlow": True,
                    "glowColor": "#ff6200",
                    "glowRadius": 10,
                    "isDotMatrix": True,
                },
                {
                    "id": "route_codes",
                    "label": "Route / Terminal Stations",
                    "defaultValue": "MLDT < > SMVT",
                    "placeholder": "MLDT < > SMVT",
                    "x": 62,
                    "y": 12,
                    "width": 60,
                    "height": 9,
                    "fontFamily": "'VT323', 'Share Tech Mono', monospace",
                    "fontSize": 66,
                    "fontWeight": 700,
                    "color": "#ff9f1c",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 6,
                    "ledGlow": True,
                    "glowColor": "#ff6200",
                    "glowRadius": 12,
                    "isDotMatrix": True,
                },
                {
                    "id": "train_name_top",
                    "label": "Main Train Name (Top Display)",
                    "defaultValue": "AMRIT BHARAT EXPRESS",
                    "placeholder": "AMRIT BHARAT EXPRESS",
                    "x": 50,
                    "y": 27,
                    "width": 92,
                    "height": 11,
                    "fontFamily": "'VT323', 'DotGothic16', monospace",
                    "fontSize": 78,
                    "fontWeight": 700,
                    "color": "#ff9f1c",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 6,
                    "ledGlow": True,
                    "glowColor": "#ff6200",
                    "glowRadius": 14,
                    "isDotMatrix": True,
                },
                {
                    "id": "train_name_bottom",
                    "label": "Reverse / Return Train Name (Bottom Display)",
                    "defaultValue": "SMVT BENGALURU ➔ MALDA TOWN",
                    "placeholder": "ENTER BOTTOM BOARD TEXT",
                    "x": 50,
                    "y": 55,
                    "width": 92,
                    "height": 11,
                    "fontFamily": "'VT323', 'DotGothic16', monospace",
                    "fontSize": 60,
                    "fontWeight": 700,
                    "color": "#ff9f1c",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 4,
                    "ledGlow": True,
                    "glowColor": "#ff6200",
                    "glowRadius": 12,
                    "isDotMatrix": True,
                }
            ],
            "fixed_graphics": [],
        },
        {
            "id": "gjs-productions-led-1024",
            "name": "GJS Productions 4-Row LED Coach Sheet",
            "category": "LED Texture Sheet",
            "description": "1024×1024 4-Row amber glowing LED destination display texture sheet matching simulator UV layout.",
            "base_width": 1024,
            "base_height": 1024,
            "background_image_url": "/textures/gjs_productions_led_sheet.png",
            "is_paid": True,
            "price": Decimal("99.00"),
            "published": True,
            "fields": [
                {
                    "id": "led_row_1",
                    "label": "Board Display Row 1",
                    "defaultValue": "GJS PRODUCTIONS",
                    "placeholder": "ENTER TEXT ROW 1",
                    "x": 48,
                    "y": 53,
                    "width": 82,
                    "height": 9,
                    "fontFamily": "'DotGothic16', 'VT323', monospace",
                    "fontSize": 54,
                    "fontWeight": 700,
                    "color": "#ffb703",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 5,
                    "ledGlow": True,
                    "glowColor": "#fb8500",
                    "glowRadius": 14,
                    "isDotMatrix": True,
                },
                {
                    "id": "led_row_2",
                    "label": "Board Display Row 2",
                    "defaultValue": "GJS PRODUCTIONS",
                    "placeholder": "ENTER TEXT ROW 2",
                    "x": 48,
                    "y": 67,
                    "width": 82,
                    "height": 9,
                    "fontFamily": "'DotGothic16', 'VT323', monospace",
                    "fontSize": 54,
                    "fontWeight": 700,
                    "color": "#ffb703",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 5,
                    "ledGlow": True,
                    "glowColor": "#fb8500",
                    "glowRadius": 14,
                    "isDotMatrix": True,
                },
                {
                    "id": "led_row_3",
                    "label": "Board Display Row 3",
                    "defaultValue": "GJS PRODUCTIONS",
                    "placeholder": "ENTER TEXT ROW 3",
                    "x": 48,
                    "y": 80,
                    "width": 82,
                    "height": 9,
                    "fontFamily": "'DotGothic16', 'VT323', monospace",
                    "fontSize": 54,
                    "fontWeight": 700,
                    "color": "#ffb703",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 5,
                    "ledGlow": True,
                    "glowColor": "#fb8500",
                    "glowRadius": 14,
                    "isDotMatrix": True,
                },
                {
                    "id": "led_row_4",
                    "label": "Board Display Row 4",
                    "defaultValue": "GJS PRODUCTIONS",
                    "placeholder": "ENTER TEXT ROW 4",
                    "x": 48,
                    "y": 93,
                    "width": 82,
                    "height": 9,
                    "fontFamily": "'DotGothic16', 'VT323', monospace",
                    "fontSize": 54,
                    "fontWeight": 700,
                    "color": "#ffb703",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 5,
                    "ledGlow": True,
                    "glowColor": "#fb8500",
                    "glowRadius": 14,
                    "isDotMatrix": True,
                }
            ],
            "fixed_graphics": [],
        },
        {
            "id": "ir-coach-side-yellow",
            "name": "IR Express Coach Destination Board",
            "category": "Coach Board",
            "description": "Authentic Indian Railways coach side destination board with dual-language train names and route details.",
            "base_width": 1000,
            "base_height": 280,
            "is_paid": True,
            "price": Decimal("149.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_number",
                    "label": "Train Number",
                    "defaultValue": "12627 / 12628",
                    "placeholder": "e.g. 12627 / 12628",
                    "x": 50,
                    "y": 26,
                    "width": 90,
                    "height": 14,
                    "fontFamily": "Roboto Condensed, Impact, Arial",
                    "fontSize": 22,
                    "fontWeight": 900,
                    "color": "#a00000",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 2,
                },
                {
                    "id": "train_name_hi",
                    "label": "Train Name (Hindi)",
                    "defaultValue": "कर्नाटक सुपरफास्ट एक्सप्रेस",
                    "placeholder": "हिंदी में ट्रेन का नाम",
                    "x": 50,
                    "y": 42,
                    "width": 92,
                    "height": 17,
                    "fontFamily": "Nirmala UI, Mangal, Arial",
                    "fontSize": 26,
                    "fontWeight": 700,
                    "color": "#0b2545",
                    "align": "center",
                },
                {
                    "id": "train_name_en",
                    "label": "Train Name (English)",
                    "defaultValue": "KARNATAKA SUPERFAST EXPRESS",
                    "placeholder": "Train name in English",
                    "x": 50,
                    "y": 60,
                    "width": 94,
                    "height": 16,
                    "fontFamily": "Arial, Roboto Condensed",
                    "fontSize": 24,
                    "fontWeight": 900,
                    "color": "#0b2545",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 1.5,
                },
                {
                    "id": "route_endpoints",
                    "label": "Route (Origin ➔ Destination)",
                    "defaultValue": "KSR BENGALURU ➔ NEW DELHI · नई दिल्ली",
                    "placeholder": "e.g. ORIGIN ➔ DESTINATION",
                    "x": 50,
                    "y": 83,
                    "width": 94,
                    "height": 12,
                    "fontFamily": "Roboto Condensed, Arial",
                    "fontSize": 16,
                    "fontWeight": 700,
                    "color": "#133c55",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 1,
                }
            ],
            "fixed_graphics": [],
        },
        {
            "id": "ir-station-platform-board",
            "name": "IR Platform Station Master Board",
            "category": "Station Board",
            "description": "Trilingual station nameboard placed on platform ends with station code and altitude above mean sea level.",
            "base_width": 1000,
            "base_height": 310,
            "is_paid": False,
            "price": Decimal("0.00"),
            "published": True,
            "fields": [
                {
                    "id": "station_regional",
                    "label": "Regional Language Name",
                    "defaultValue": "ಕ್ರಾಂತಿವೀರ ಸಂಗೊಳ್ಳಿ ರಾಯಣ್ಣ ಬೆಂಗಳೂರು ನಿಲ್ದಾಣ",
                    "placeholder": "ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ನಿಲ್ದಾಣದ ಹೆಸರು",
                    "x": 50,
                    "y": 25,
                    "width": 92,
                    "height": 18,
                    "fontFamily": "Tunga, Nirmala UI, Arial",
                    "fontSize": 27,
                    "fontWeight": 700,
                    "color": "#111111",
                    "align": "center",
                },
                {
                    "id": "station_hindi",
                    "label": "Hindi Station Name",
                    "defaultValue": "क्रांतिवीर संगोल्ली रायण्णा बेंगलुरु स्टेशन",
                    "placeholder": "स्टेशन का नाम (हिंदी)",
                    "x": 50,
                    "y": 44,
                    "width": 92,
                    "height": 18,
                    "fontFamily": "Nirmala UI, Mangal, Arial",
                    "fontSize": 28,
                    "fontWeight": 700,
                    "color": "#111111",
                    "align": "center",
                },
                {
                    "id": "station_english",
                    "label": "English Station Name",
                    "defaultValue": "KSR BENGALURU CITY JN.",
                    "placeholder": "Station Name in English",
                    "x": 50,
                    "y": 63,
                    "width": 92,
                    "height": 16,
                    "fontFamily": "Arial Black, Arial, sans-serif",
                    "fontSize": 26,
                    "fontWeight": 900,
                    "color": "#111111",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 2,
                }
            ],
            "fixed_graphics": [],
        },
        {
            "id": "rajdhani-lhb-red-board",
            "name": "Rajdhani Express LHB Red Coach Board",
            "category": "Coach Board",
            "description": "Premier LHB Rajdhani Express red & silver livery destination side board.",
            "base_width": 1000,
            "base_height": 280,
            "is_paid": False,
            "price": Decimal("0.00"),
            "published": True,
            "fields": [
                {
                    "id": "train_number",
                    "label": "Train Number",
                    "defaultValue": "22691 / 22692",
                    "placeholder": "22691 / 22692",
                    "x": 50,
                    "y": 26,
                    "width": 90,
                    "height": 14,
                    "fontFamily": "Roboto Condensed, Arial",
                    "fontSize": 22,
                    "fontWeight": 900,
                    "color": "#ffbe0b",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 2,
                },
                {
                    "id": "train_name_hi",
                    "label": "Train Name (Hindi)",
                    "defaultValue": "बेंगलुरु ह. निज़ामुद्दीन राजधानी एक्सप्रेस",
                    "placeholder": "राजधानी एक्सप्रेस",
                    "x": 50,
                    "y": 45,
                    "width": 92,
                    "height": 17,
                    "fontFamily": "Nirmala UI, Arial",
                    "fontSize": 25,
                    "fontWeight": 700,
                    "color": "#ffffff",
                    "align": "center",
                },
                {
                    "id": "train_name_en",
                    "label": "Train Name (English)",
                    "defaultValue": "BENGALURU - NZM RAJDHANI EXP.",
                    "placeholder": "RAJDHANI EXPRESS",
                    "x": 50,
                    "y": 64,
                    "width": 94,
                    "height": 16,
                    "fontFamily": "Arial, Roboto Condensed",
                    "fontSize": 24,
                    "fontWeight": 900,
                    "color": "#ffffff",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 1.5,
                }
            ],
            "fixed_graphics": [],
        },
        {
            "id": "slr-guard-luggage-board",
            "name": "SLR Guard Brake & Luggage Van Board",
            "category": "SLR Board",
            "description": "Guard cabin, brake van, and parcel luggage compartment markings with red warning borders.",
            "base_width": 1000,
            "base_height": 310,
            "is_paid": False,
            "price": Decimal("0.00"),
            "published": True,
            "fields": [
                {
                    "id": "slr_train_info",
                    "label": "Train Number & Destination",
                    "defaultValue": "12627 KARNATAKA EXPRESS",
                    "placeholder": "TRAIN INFO",
                    "x": 50,
                    "y": 28,
                    "width": 92,
                    "height": 18,
                    "fontFamily": "Roboto Condensed, Impact, Arial",
                    "fontSize": 26,
                    "fontWeight": 900,
                    "color": "#111111",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 2,
                },
                {
                    "id": "luggage_capacity",
                    "label": "Luggage Compartment Capacity",
                    "defaultValue": "LUGGAGE COMPARTMENT · CAPACITY: 4.0 TONNES",
                    "placeholder": "CAPACITY",
                    "x": 50,
                    "y": 52,
                    "width": 92,
                    "height": 16,
                    "fontFamily": "Arial, sans-serif",
                    "fontSize": 20,
                    "fontWeight": 700,
                    "color": "#d90429",
                    "align": "center",
                    "textTransform": "uppercase",
                    "letterSpacing": 1.5,
                }
            ],
            "fixed_graphics": [],
        }
    ]

    for item in templates_data:
        BoardTemplate.objects.update_or_create(id=item["id"], defaults=item)

def unseed_gjs_nm_editor_templates(apps, schema_editor):
    BoardTemplate = apps.get_model("store", "BoardTemplate")
    BoardTemplate.objects.filter(id__in=[
        "amrit-bharat-led-1024",
        "gjs-productions-led-1024",
        "ir-coach-side-yellow",
        "ir-station-platform-board",
        "rajdhani-lhb-red-board",
        "slr-guard-luggage-board"
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("store", "0037_seed_board_templates"),
    ]

    operations = [
        migrations.RunPython(seed_gjs_nm_editor_templates, unseed_gjs_nm_editor_templates),
    ]

