# Generated by Django 5.2.15 on 2026-09-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_seed_gjs_nm_editor_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='board_template',
            field=models.ForeignKey(blank=True, help_text='Associated Board Template for trainset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='store.boardtemplate'),
        ),
        migrations.AddField(
            model_name='boardtemplate',
            name='target_texture_name',
            field=models.CharField(blank=True, default='', help_text='Target texture filename required by MSTS/Open Rails 3D model, e.g. VB_NAME.dds', max_length=120),
        ),
    ]
