# Generated by Django 5.2.17 on 2026-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_asset_board_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bundle_board_template_free',
            field=models.BooleanField(default=False, help_text='Bundle associated board template for free when user purchases this asset at single price'),
        ),
    ]
