# Generated by Django 5.2.17 on 2026-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_asset_bundle_board_template_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtemplate',
            name='variations',
            field=models.JSONField(blank=True, default=list, help_text='Style variations for this template designed by admin'),
        ),
        migrations.AlterField(
            model_name='boardtemplate',
            name='background_image_url',
            field=models.TextField(blank=True, default='', help_text='Background image URL or data URI'),
        ),
    ]
