# Generated by Django 5.2.17 on 2026-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_boardtemplate_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Customer 10-digit mobile number for Cashfree payment gateway & invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='board_studio_enabled',
            field=models.BooleanField(default=True, help_text='Toggle public visibility of Railway Board Studio on the website'),
        ),
    ]
