# Generated by Django on 2026-09-16
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_user_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('store', 'UserProfile')
    Order = apps.get_model('store', 'Order')

    for user in User.objects.all():
        profile, created = UserProfile.objects.get_or_create(user=user)
        if not profile.phone_number:
            latest_order = Order.objects.filter(user=user).exclude(customer_phone="").order_by("-id").first()
            if latest_order and latest_order.customer_phone:
                profile.phone_number = latest_order.customer_phone
                profile.save(update_fields=["phone_number"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0042_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', help_text='10-digit mobile number for order delivery, SMS notifications, and Cashfree gateway.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RunPython(populate_user_profiles, reverse_code=migrations.RunPython.noop),
    ]

