# Generated by Django 5.2.17 on 2026-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtemplate',
            name='allow_user_edit_texture_name',
            field=models.BooleanField(default=False, help_text='Allow regular users to customize/rename the export texture filename in editor'),
        ),
    ]
