# Generated by Django 5.2.17 on 2026-09-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_add_nameboard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtemplate',
            name='quick_presets',
            field=models.JSONField(blank=True, default=list, help_text='Quick preset train names and values designed by admin'),
        ),
    ]
