# Generated by Django 5.2.17 on 2026-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_boardtemplate_quick_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='special_access_email_body',
            field=models.TextField(default='Great news! You have been granted exclusive Special Access on MSTS-GJS Production Store. You now have complimentary access to download premium Indian Railways train packs and simulator addons with VIP privileges. Log in to your account and explore the depot!', help_text='Common message body for special access announcement emails. Supports placeholders: {username}, {access_type}, {granted_items}, {expiry_info}, {store_url}'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='special_access_email_footer',
            field=models.CharField(default='Happy Simulating! — MSTS-GJS Production Team', help_text='Sign-off note at the bottom of the announcement email', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='special_access_email_heading',
            field=models.CharField(default='VIP Special Access Granted', help_text='Header title inside the special access announcement email', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='special_access_email_subject',
            field=models.CharField(default="🎉 You've Received VIP Special Access - MSTS-GJS Production Store", help_text='Default subject for special access email announcements', max_length=200),
        ),
    ]
