# Generated by Django 5.2.17 on 2026-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_sitesetting_special_access_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deal_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='prebooking_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
