# Generated by Django 5.2.17 on 2026-09-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_asset_deal_starts_at_asset_prebooking_ends_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAccessInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(default='VIP Special Access Invite', max_length=160)),
                ('mode', models.CharField(choices=[('APPROVAL', 'Request Mode (Admin Approves)'), ('AUTO_GRANT', 'Instant Claim (Auto-Grant Access)')], default='APPROVAL', max_length=24)),
                ('is_all_access_free', models.BooleanField(default=True, help_text='When true, grants Storewide Free All-Access Pass.')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of approved claims allowed (0 = unlimited).')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('access_expires_at', models.DateTimeField(blank=True, help_text="Optional expiration date for the user's granted special access.", null=True)),
                ('link_expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this invite link itself.', null=True)),
                ('admin_note', models.CharField(blank=True, default='', help_text='Internal note for admins.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_access_links', to=settings.AUTH_USER_MODEL)),
                ('granted_assets', models.ManyToManyField(blank=True, help_text='Specific assets granted if all-access is false.', related_name='special_access_invite_links', to='store.asset')),
            ],
            options={
                'verbose_name': 'Special access invite link',
                'verbose_name_plural': 'Special access invite links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialAccessClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_note', models.CharField(blank=True, default='', help_text='Message or note submitted by the requester.', max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Granted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_special_access_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_access_requests', to=settings.AUTH_USER_MODEL)),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='store.specialaccessinvitelink')),
            ],
            options={
                'verbose_name': 'Special access claim request',
                'verbose_name_plural': 'Special access claim requests',
                'ordering': ['-created_at'],
                'unique_together': {('invite_link', 'user')},
            },
        ),
    ]
