# Generated by Django 5.2.17 on 2026-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_specialaccessinvitelink_specialaccessclaimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialaccessinvitelink',
            name='granted_board_templates',
            field=models.ManyToManyField(blank=True, help_text='Specific nameboard templates granted if all-access is false.', related_name='special_access_invite_links', to='store.boardtemplate'),
        ),
        migrations.AddField(
            model_name='userspecialaccess',
            name='granted_board_templates',
            field=models.ManyToManyField(blank=True, help_text='Specific nameboard templates granted for free if all-access is false.', related_name='special_access_users', to='store.boardtemplate'),
        ),
    ]
