import { BoardTemplate } from './types';

export const DEFAULT_TEMPLATES: BoardTemplate[] = [
  // 1. AMRIT BHARAT LED 1024x1024 TEXTURE SHEET
  {
    id: 'amrit-bharat-led-1024',
    name: 'Amrit Bharat LED 1024×1024 Texture Sheet',
    category: 'LED Texture Sheet',
    description: 'Authentic 1024×1024 Train Simulator UV texture sheet with glowing amber LED destination displays for Amrit Bharat Express.',
    aspectRatio: '1:1',
    baseWidth: 1024,
    baseHeight: 1024,
    backgroundColor: '#0c0f12',
    backgroundType: 'transparent',
    backgroundImageUrl: '/textures/amrit_bharat_led_sheet.png',
    isTextureSheet: true,
    textureResolution: 1024,
    borderColor: '#33404d',
    borderWidth: 1,
    borderRadius: 0,
    showBolts: false,
    fixedGraphics: [],
    fields: [
      {
        id: 'train_no_up',
        label: 'Train Number (Up)',
        defaultValue: '13433',
        placeholder: '13433',
        x: 18,
        y: 9,
        width: 20,
        height: 7,
        fontFamily: "'VT323', 'DotGothic16', monospace",
        fontSize: 52,
        fontWeight: 700,
        color: '#ff9f1c',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 4,
        ledGlow: true,
        glowColor: '#ff6200',
        glowRadius: 10,
        isDotMatrix: true,
        helpText: 'Top Train Number (e.g. 13433)'
      },
      {
        id: 'train_no_dn',
        label: 'Train Number (Down)',
        defaultValue: '13434',
        placeholder: '13434',
        x: 18,
        y: 15,
        width: 20,
        height: 7,
        fontFamily: "'VT323', 'DotGothic16', monospace",
        fontSize: 52,
        fontWeight: 700,
        color: '#ff9f1c',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 4,
        ledGlow: true,
        glowColor: '#ff6200',
        glowRadius: 10,
        isDotMatrix: true,
        helpText: 'Bottom Train Number (e.g. 13434)'
      },
      {
        id: 'route_codes',
        label: 'Route / Terminal Stations',
        defaultValue: 'MLDT < > SMVT',
        placeholder: 'MLDT < > SMVT',
        x: 62,
        y: 12,
        width: 60,
        height: 9,
        fontFamily: "'VT323', 'Share Tech Mono', monospace",
        fontSize: 66,
        fontWeight: 700,
        color: '#ff9f1c',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 6,
        ledGlow: true,
        glowColor: '#ff6200',
        glowRadius: 12,
        isDotMatrix: true,
        helpText: 'Origin and Destination station codes'
      },
      {
        id: 'train_name_top',
        label: 'Main Train Name (Top Display)',
        defaultValue: 'AMRIT BHARAT EXPRESS',
        placeholder: 'AMRIT BHARAT EXPRESS',
        x: 50,
        y: 27,
        width: 92,
        height: 11,
        fontFamily: "'VT323', 'DotGothic16', monospace",
        fontSize: 78,
        fontWeight: 700,
        color: '#ff9f1c',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 6,
        ledGlow: true,
        glowColor: '#ff6200',
        glowRadius: 14,
        isDotMatrix: true,
        helpText: 'Full Train Name in LED segment font'
      },
      {
        id: 'train_name_bottom',
        label: 'Reverse / Return Train Name (Bottom Display)',
        defaultValue: 'SMVT BENGALURU ➔ MALDA TOWN',
        placeholder: 'ENTER BOTTOM BOARD TEXT',
        x: 50,
        y: 55,
        width: 92,
        height: 11,
        fontFamily: "'VT323', 'DotGothic16', monospace",
        fontSize: 60,
        fontWeight: 700,
        color: '#ff9f1c',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 4,
        ledGlow: true,
        glowColor: '#ff6200',
        glowRadius: 12,
        isDotMatrix: true,
        helpText: 'Empty board slot for reverse or alternate coach display'
      }
    ],
    quickPresets: [
      {
        id: 'preset-amrit-delhi',
        name: 'Darbhanga - Delhi',
        description: '15557 / 15558 Amrit Bharat Express DBG < > ANVT',
        values: {
          train_no_up: '15557',
          train_no_dn: '15558',
          route_codes: 'DBG < > ANVT',
          train_name_top: 'AMRIT BHARAT EXPRESS',
          train_name_bottom: 'अमृत भारत एक्सप्रेस'
        }
      },
      {
        id: 'preset-amrit-howrah',
        name: 'Howrah - Balurghat',
        description: '13063 / 13064 Amrit Bharat Express HWH < > BLGT',
        values: {
          train_no_up: '13063',
          train_no_dn: '13064',
          route_codes: 'HWH < > BLGT',
          train_name_top: 'AMRIT BHARAT EXPRESS',
          train_name_bottom: 'अमृत भारत एक्सप्रेस'
        }
      },
      {
        id: 'preset-amrit-malda',
        name: 'Malda Town - SMVT',
        description: '13433 / 13434 Amrit Bharat Express MLDT < > SMVT',
        values: {
          train_no_up: '13433',
          train_no_dn: '13434',
          route_codes: 'MLDT < > SMVT',
          train_name_top: 'AMRIT BHARAT EXPRESS',
          train_name_bottom: 'अमृत भारत एक्सप्रेस'
        }
      }
    ],
    published: true,
    createdAt: '2026-09-14T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
    author: 'Admin'
  },

  // 2. GJS PRODUCTIONS 4-ROW LED COACH SHEET
  {
    id: 'gjs-productions-led-1024',
    name: 'GJS Productions 4-Row LED Coach Sheet',
    category: 'LED Texture Sheet',
    description: '1024×1024 4-Row amber glowing LED destination display texture sheet matching simulator UV layout.',
    aspectRatio: '1:1',
    baseWidth: 1024,
    baseHeight: 1024,
    backgroundColor: '#000000',
    backgroundType: 'transparent',
    backgroundImageUrl: '/textures/gjs_productions_led_sheet.png',
    isTextureSheet: true,
    textureResolution: 1024,
    borderColor: '#33404d',
    borderWidth: 1,
    borderRadius: 0,
    showBolts: false,
    fixedGraphics: [],
    fields: [
      {
        id: 'led_row_1',
        label: 'Board Display Row 1',
        defaultValue: 'GJS PRODUCTIONS',
        placeholder: 'ENTER TEXT ROW 1',
        x: 48,
        y: 53,
        width: 82,
        height: 9,
        fontFamily: "'DotGothic16', 'VT323', monospace",
        fontSize: 54,
        fontWeight: 700,
        color: '#ffb703',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 5,
        ledGlow: true,
        glowColor: '#fb8500',
        glowRadius: 14,
        isDotMatrix: true
      },
      {
        id: 'led_row_2',
        label: 'Board Display Row 2',
        defaultValue: 'GJS PRODUCTIONS',
        placeholder: 'ENTER TEXT ROW 2',
        x: 48,
        y: 67,
        width: 82,
        height: 9,
        fontFamily: "'DotGothic16', 'VT323', monospace",
        fontSize: 54,
        fontWeight: 700,
        color: '#ffb703',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 5,
        ledGlow: true,
        glowColor: '#fb8500',
        glowRadius: 14,
        isDotMatrix: true
      },
      {
        id: 'led_row_3',
        label: 'Board Display Row 3',
        defaultValue: 'GJS PRODUCTIONS',
        placeholder: 'ENTER TEXT ROW 3',
        x: 48,
        y: 80,
        width: 82,
        height: 9,
        fontFamily: "'DotGothic16', 'VT323', monospace",
        fontSize: 54,
        fontWeight: 700,
        color: '#ffb703',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 5,
        ledGlow: true,
        glowColor: '#fb8500',
        glowRadius: 14,
        isDotMatrix: true
      },
      {
        id: 'led_row_4',
        label: 'Board Display Row 4',
        defaultValue: 'GJS PRODUCTIONS',
        placeholder: 'ENTER TEXT ROW 4',
        x: 48,
        y: 93,
        width: 82,
        height: 9,
        fontFamily: "'DotGothic16', 'VT323', monospace",
        fontSize: 54,
        fontWeight: 700,
        color: '#ffb703',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 5,
        ledGlow: true,
        glowColor: '#fb8500',
        glowRadius: 14,
        isDotMatrix: true
      }
    ],
    quickPresets: [
      {
        id: 'preset-gjs-karnataka',
        name: 'Karnataka Express',
        description: '12627 / 12628 SBC < > NDLS Superfast Express',
        values: {
          led_row_1: 'KARNATAKA EXP',
          led_row_2: 'SBC < > NDLS',
          led_row_3: 'SUPERFAST EXPRESS',
          led_row_4: 'VIA PUNE - MANMAD'
        }
      },
      {
        id: 'preset-gjs-tamil-nadu',
        name: 'Tamil Nadu Exp',
        description: '12621 / 12622 MAS < > NDLS Superfast Express',
        values: {
          led_row_1: 'TAMIL NADU EXP',
          led_row_2: 'MAS < > NDLS',
          led_row_3: 'SUPERFAST EXPRESS',
          led_row_4: 'VIA VIJAYAWADA - NAGPUR'
        }
      },
      {
        id: 'preset-gjs-amrit-bharat',
        name: 'Amrit Bharat Exp',
        description: '15557 / 15558 DBG < > ANVT Express',
        values: {
          led_row_1: 'AMRIT BHARAT',
          led_row_2: 'DBG < > ANVT',
          led_row_3: 'SUPERFAST EXPRESS',
          led_row_4: 'INDIAN RAILWAYS'
        }
      }
    ],
    published: true,
    isPaid: true,
    price: 99,
    currency: '₹',
    createdAt: '2026-09-14T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
    author: 'Admin',
    variations: [
      {
        id: 'var_amrit_orange',
        name: 'Saffron & Amber LED Matrix',
        description: 'Authentic glowing Saffron/Amber LED dot-matrix destination display',
        targetTextureName: 'AMRIT_LED',
        fields: [
          {
            id: 'train_no_up',
            label: 'Train Number (Up)',
            defaultValue: '13433',
            placeholder: '13433',
            x: 18,
            y: 9,
            width: 20,
            height: 7,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 52,
            fontWeight: 700,
            color: '#ff9f1c',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#ff6200',
            glowRadius: 10,
            isDotMatrix: true
          },
          {
            id: 'train_no_dn',
            label: 'Train Number (Down)',
            defaultValue: '13434',
            placeholder: '13434',
            x: 18,
            y: 15,
            width: 20,
            height: 7,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 52,
            fontWeight: 700,
            color: '#ff9f1c',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#ff6200',
            glowRadius: 10,
            isDotMatrix: true
          },
          {
            id: 'route_codes',
            label: 'Route / Terminal Stations',
            defaultValue: 'MLDT < > SMVT',
            placeholder: 'MLDT < > SMVT',
            x: 62,
            y: 12,
            width: 60,
            height: 9,
            fontFamily: "'VT323', 'Share Tech Mono', monospace",
            fontSize: 66,
            fontWeight: 700,
            color: '#ff9f1c',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 6,
            ledGlow: true,
            glowColor: '#ff6200',
            glowRadius: 12,
            isDotMatrix: true
          },
          {
            id: 'train_name_top',
            label: 'Main Train Name (Top Display)',
            defaultValue: 'AMRIT BHARAT EXPRESS',
            placeholder: 'AMRIT BHARAT EXPRESS',
            x: 50,
            y: 27,
            width: 92,
            height: 11,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 78,
            fontWeight: 700,
            color: '#ff9f1c',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 6,
            ledGlow: true,
            glowColor: '#ff6200',
            glowRadius: 14,
            isDotMatrix: true
          }
        ]
      },
      {
        id: 'var_amrit_ice_blue',
        name: 'Deep Ice Blue Matrix',
        description: 'Modern night run Ice Blue LED dot-matrix display',
        targetTextureName: 'AMRIT_LED_BLUE',
        fields: [
          {
            id: 'train_no_up',
            label: 'Train Number (Up)',
            defaultValue: '13433',
            placeholder: '13433',
            x: 18,
            y: 9,
            width: 20,
            height: 7,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 52,
            fontWeight: 700,
            color: '#00e5ff',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#0077ff',
            glowRadius: 12,
            isDotMatrix: true
          },
          {
            id: 'train_no_dn',
            label: 'Train Number (Down)',
            defaultValue: '13434',
            placeholder: '13434',
            x: 18,
            y: 15,
            width: 20,
            height: 7,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 52,
            fontWeight: 700,
            color: '#00e5ff',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#0077ff',
            glowRadius: 12,
            isDotMatrix: true
          },
          {
            id: 'route_codes',
            label: 'Route / Terminal Stations',
            defaultValue: 'MLDT < > SMVT',
            placeholder: 'MLDT < > SMVT',
            x: 62,
            y: 12,
            width: 60,
            height: 9,
            fontFamily: "'VT323', 'Share Tech Mono', monospace",
            fontSize: 66,
            fontWeight: 700,
            color: '#00e5ff',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 6,
            ledGlow: true,
            glowColor: '#0077ff',
            glowRadius: 14,
            isDotMatrix: true
          },
          {
            id: 'train_name_top',
            label: 'Main Train Name (Top Display)',
            defaultValue: 'AMRIT BHARAT EXPRESS',
            placeholder: 'AMRIT BHARAT EXPRESS',
            x: 50,
            y: 27,
            width: 92,
            height: 11,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 78,
            fontWeight: 700,
            color: '#00e5ff',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 6,
            ledGlow: true,
            glowColor: '#0077ff',
            glowRadius: 16,
            isDotMatrix: true
          }
        ]
      },
      {
        id: 'var_amrit_dual_lang',
        name: 'Bilingual Dual Line (Hindi + English)',
        description: 'Two-tier Indian Railways display with Devanagari Hindi & English',
        targetTextureName: 'AMRIT_LED_HIN',
        fields: [
          {
            id: 'train_no_up',
            label: 'Train Number (Up)',
            defaultValue: '13433',
            placeholder: '13433',
            x: 18,
            y: 9,
            width: 20,
            height: 7,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 52,
            fontWeight: 700,
            color: '#ffb703',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#fb8500',
            glowRadius: 10,
            isDotMatrix: true
          },
          {
            id: 'train_no_dn',
            label: 'Train Number (Down)',
            defaultValue: '13434',
            placeholder: '13434',
            x: 18,
            y: 15,
            width: 20,
            height: 7,
            fontFamily: "'VT323', 'DotGothic16', monospace",
            fontSize: 52,
            fontWeight: 700,
            color: '#ffb703',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#fb8500',
            glowRadius: 10,
            isDotMatrix: true
          },
          {
            id: 'route_codes',
            label: 'Route / Terminal Stations',
            defaultValue: 'मालदा टाउन < > सर एम. विश्वेश्वरय्या टर्मिनल',
            placeholder: 'मालदा टाउन < > एसएमवीटी',
            x: 62,
            y: 12,
            width: 60,
            height: 9,
            fontFamily: "'DotGothic16', 'VT323', sans-serif",
            fontSize: 48,
            fontWeight: 700,
            color: '#ffb703',
            align: 'center',
            textTransform: 'none',
            letterSpacing: 2,
            ledGlow: true,
            glowColor: '#fb8500',
            glowRadius: 10,
            isDotMatrix: true
          },
          {
            id: 'train_name_top',
            label: 'Main Train Name (Hindi)',
            defaultValue: 'अमृत भारत एक्सप्रेस',
            placeholder: 'अमृत भारत एक्सप्रेस',
            x: 50,
            y: 27,
            width: 92,
            height: 11,
            fontFamily: "'DotGothic16', 'VT323', sans-serif",
            fontSize: 68,
            fontWeight: 700,
            color: '#ffb703',
            align: 'center',
            textTransform: 'none',
            letterSpacing: 4,
            ledGlow: true,
            glowColor: '#fb8500',
            glowRadius: 12,
            isDotMatrix: true
          }
        ]
      },
      {
        id: 'var_amrit_sleeper',
        name: 'Sleeper Class Side Board',
        description: 'Classic non-AC Sleeper Coach exterior destination board',
        targetTextureName: 'AMRIT_SL_BOARD',
        fields: [
          {
            id: 'train_no_up',
            label: 'Train Number',
            defaultValue: '13433 / 13434',
            placeholder: '13433 / 13434',
            x: 50,
            y: 9,
            width: 80,
            height: 7,
            fontFamily: "Arial, sans-serif",
            fontSize: 44,
            fontWeight: 700,
            color: '#ffffff',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 3,
            ledGlow: false,
            isDotMatrix: false
          },
          {
            id: 'route_codes',
            label: 'Route Stations',
            defaultValue: 'MALDA TOWN  ↔  SMVT BENGALURU',
            placeholder: 'ORIGIN ↔ DESTINATION',
            x: 50,
            y: 18,
            width: 90,
            height: 8,
            fontFamily: "Arial, sans-serif",
            fontSize: 50,
            fontWeight: 700,
            color: '#ffd166',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 4,
            ledGlow: false,
            isDotMatrix: false
          },
          {
            id: 'train_name_top',
            label: 'Coach Type / Class',
            defaultValue: 'NON-AC SLEEPER CLASS • AMRIT BHARAT',
            placeholder: 'CLASS DETAILS',
            x: 50,
            y: 27,
            width: 92,
            height: 9,
            fontFamily: "Arial, sans-serif",
            fontSize: 42,
            fontWeight: 700,
            color: '#ffffff',
            align: 'center',
            textTransform: 'uppercase',
            letterSpacing: 3,
            ledGlow: false,
            isDotMatrix: false
          }
        ]
      }
    ]
  },

  // 3. IR EXPRESS COACH DESTINATION BOARD
  {
    id: 'ir-coach-side-yellow',
    name: 'IR Express Coach Destination Board',
    category: 'Coach Board',
    description: 'Authentic Indian Railways coach side destination board with dual-language train names and route details.',
    aspectRatio: '16:4.5',
    baseWidth: 1000,
    baseHeight: 280,
    backgroundColor: '#ffbe0b',
    backgroundSecondaryColor: '#ffa000',
    backgroundType: 'gradient',
    borderColor: '#0b2545',
    borderWidth: 6,
    borderRadius: 8,
    innerBorder: true,
    innerBorderColor: '#0b2545',
    innerBorderPadding: 6,
    showBolts: true,
    fixedGraphics: [
      {
        id: 'header-title-hi',
        type: 'text',
        content: 'भारतीय रेल',
        x: 18,
        y: 6,
        fontSize: 14,
        fontWeight: 700,
        fontFamily: 'Nirmala UI, Arial',
        color: '#0b2545',
        align: 'center'
      },
      {
        id: 'header-title-en',
        type: 'text',
        content: 'INDIAN RAILWAYS',
        x: 82,
        y: 6,
        fontSize: 13,
        fontWeight: 700,
        fontFamily: 'Roboto Condensed, Arial',
        color: '#0b2545',
        align: 'center'
      },
      {
        id: 'header-divider',
        type: 'divider',
        x: 2,
        y: 22,
        width: 96,
        height: 1,
        color: '#0b2545'
      },
      {
        id: 'footer-divider',
        type: 'divider',
        x: 2,
        y: 78,
        width: 96,
        height: 1,
        color: '#0b2545'
      }
    ],
    fields: [
      {
        id: 'train_number',
        label: 'Train Number',
        defaultValue: '12627 / 12628',
        placeholder: 'e.g. 12627 / 12628',
        x: 50,
        y: 26,
        width: 90,
        height: 14,
        fontFamily: 'Roboto Condensed, Impact, Arial',
        fontSize: 22,
        fontWeight: 900,
        color: '#a00000',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 2
      },
      {
        id: 'train_name_hi',
        label: 'Train Name (Hindi)',
        defaultValue: 'कर्नाटक सुपरफास्ट एक्सप्रेस',
        placeholder: 'हिंदी में ट्रेन का नाम',
        x: 50,
        y: 42,
        width: 92,
        height: 17,
        fontFamily: 'Nirmala UI, Mangal, Arial',
        fontSize: 26,
        fontWeight: 700,
        color: '#0b2545',
        align: 'center'
      },
      {
        id: 'train_name_en',
        label: 'Train Name (English)',
        defaultValue: 'KARNATAKA SUPERFAST EXPRESS',
        placeholder: 'Train name in English',
        x: 50,
        y: 60,
        width: 94,
        height: 16,
        fontFamily: 'Arial, Roboto Condensed',
        fontSize: 24,
        fontWeight: 900,
        color: '#0b2545',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1.5
      },
      {
        id: 'route_endpoints',
        label: 'Route (Origin ➔ Destination)',
        defaultValue: 'KSR BENGALURU ➔ NEW DELHI · नई दिल्ली',
        placeholder: 'e.g. ORIGIN ➔ DESTINATION',
        x: 50,
        y: 83,
        width: 94,
        height: 12,
        fontFamily: 'Roboto Condensed, Arial',
        fontSize: 16,
        fontWeight: 700,
        color: '#133c55',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1
      }
    ],
    quickPresets: [
      {
        id: 'preset-coach-tamil-nadu',
        name: 'Tamil Nadu Exp',
        description: '12621 / 12622 MAS < > NDLS Superfast Express',
        values: {
          train_number: '12621 / 12622',
          train_name_hi: 'तमिलनाडु एक्सप्रेस',
          train_name_en: 'TAMIL NADU EXPRESS',
          route_endpoints: 'चेन्नै सेंट्रल  MGR CHENNAI CTL < > NEW DELHI  नई दिल्ली'
        }
      },
      {
        id: 'preset-coach-karnataka',
        name: 'Karnataka Express',
        description: '12627 / 12628 SBC < > NDLS Superfast Express',
        values: {
          train_number: '12627 / 12628',
          train_name_hi: 'कर्नाटक एक्सप्रेस',
          train_name_en: 'KARNATAKA EXPRESS',
          route_endpoints: 'केएसआर बेंगलूरु  KSR BENGALURU < > NEW DELHI  नई दिल्ली'
        }
      },
      {
        id: 'preset-coach-grand-trunk',
        name: 'Grand Trunk Express',
        description: '12615 / 12616 MAS < > NDLS Superfast Express',
        values: {
          train_number: '12615 / 12616',
          train_name_hi: 'ग्रैंड ट्रंक एक्सप्रेस',
          train_name_en: 'GRAND TRUNK EXPRESS',
          route_endpoints: 'चेन्नै सेंट्रल  MAS < > NEW DELHI  नई दिल्ली'
        }
      }
    ],
    published: true,
    isPaid: true,
    price: 149,
    currency: '₹',
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
    author: 'System Admin'
  },

  // 4. IR PLATFORM STATION MASTER BOARD
  {
    id: 'ir-station-platform-board',
    name: 'IR Platform Station Master Board',
    category: 'Station Board',
    description: 'Trilingual station nameboard placed on platform ends with station code and altitude above mean sea level.',
    aspectRatio: '16:5',
    baseWidth: 1000,
    baseHeight: 310,
    backgroundColor: '#ffc800',
    backgroundType: 'solid',
    borderColor: '#111111',
    borderWidth: 8,
    borderRadius: 6,
    innerBorder: true,
    innerBorderColor: '#111111',
    innerBorderPadding: 7,
    showBolts: true,
    fixedGraphics: [
      {
        id: 'division-stamp',
        type: 'text',
        content: 'SOUTH WESTERN RAILWAY · हुब्बल्लि मंडल',
        x: 50,
        y: 6,
        fontSize: 13,
        fontWeight: 700,
        fontFamily: 'Arial',
        color: '#111111',
        align: 'center'
      },
      {
        id: 'header-divider',
        type: 'divider',
        x: 2,
        y: 19,
        width: 96,
        height: 2,
        color: '#111111'
      },
      {
        id: 'footer-divider',
        type: 'divider',
        x: 2,
        y: 81,
        width: 96,
        height: 2,
        color: '#111111'
      }
    ],
    fields: [
      {
        id: 'station_regional',
        label: 'Regional Language Name (e.g. Kannada/Tamil)',
        defaultValue: 'ಕ್ರಾಂತಿವೀರ ಸಂಗೊಳ್ಳಿ ರಾಯಣ್ಣ ಬೆಂಗಳೂರು ನಿಲ್ದಾಣ',
        placeholder: 'ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ನಿಲ್ದಾಣದ ಹೆಸರು',
        x: 50,
        y: 25,
        width: 92,
        height: 18,
        fontFamily: 'Tunga, Nirmala UI, Arial',
        fontSize: 27,
        fontWeight: 700,
        color: '#111111',
        align: 'center'
      },
      {
        id: 'station_hindi',
        label: 'Hindi Station Name',
        defaultValue: 'क्रांतिवीर संगोल्ली रायण्णा बेंगलुरु स्टेशन',
        placeholder: 'स्टेशन का नाम (हिंदी)',
        x: 50,
        y: 44,
        width: 92,
        height: 18,
        fontFamily: 'Nirmala UI, Mangal, Arial',
        fontSize: 28,
        fontWeight: 700,
        color: '#111111',
        align: 'center'
      },
      {
        id: 'station_english',
        label: 'English Station Name',
        defaultValue: 'KSR BENGALURU CITY JN.',
        placeholder: 'Station Name in English',
        x: 50,
        y: 63,
        width: 92,
        height: 16,
        fontFamily: 'Arial Black, Arial, sans-serif',
        fontSize: 26,
        fontWeight: 900,
        color: '#111111',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 2
      },
      {
        id: 'station_code_msl',
        label: 'Station Code & Altitude (MSL)',
        defaultValue: 'CODE: SBC  |  समुद्र तल से ऊँचाई 920 मी.  |  +920 MTR. ABOVE MSL',
        placeholder: 'CODE: XXX | +XXX MTR. ABOVE MSL',
        x: 50,
        y: 87,
        width: 94,
        height: 11,
        fontFamily: 'Roboto Condensed, Arial',
        fontSize: 14,
        fontWeight: 700,
        color: '#222222',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1
      }
    ],
    published: true,
    createdAt: '2026-09-02T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
    author: 'System Admin'
  },

  // 5. RAJDHANI / LHB RED COACH BOARD
  {
    id: 'rajdhani-lhb-red-board',
    name: 'Rajdhani Express LHB Red Coach Board',
    category: 'Coach Board',
    description: 'Premier LHB Rajdhani Express red & silver livery destination side board.',
    aspectRatio: '16:4.5',
    baseWidth: 1000,
    baseHeight: 280,
    backgroundColor: '#b7094c',
    backgroundSecondaryColor: '#890620',
    backgroundType: 'gradient',
    borderColor: '#e5e5e5',
    borderWidth: 6,
    borderRadius: 8,
    innerBorder: true,
    innerBorderColor: '#e5e5e5',
    innerBorderPadding: 6,
    showBolts: true,
    fixedGraphics: [
      {
        id: 'rajdhani-brand-hi',
        type: 'text',
        content: 'राजधानी एक्सप्रेस',
        x: 20,
        y: 6,
        fontSize: 14,
        fontWeight: 700,
        fontFamily: 'Nirmala UI, Arial',
        color: '#ffffff',
        align: 'center'
      },
      {
        id: 'rajdhani-brand-en',
        type: 'text',
        content: 'RAJDHANI EXPRESS',
        x: 80,
        y: 6,
        fontSize: 13,
        fontWeight: 700,
        fontFamily: 'Roboto Condensed, Arial',
        color: '#ffffff',
        align: 'center'
      }
    ],
    fields: [
      {
        id: 'train_number',
        label: 'Train Number',
        defaultValue: '22691 / 22692',
        placeholder: '22691 / 22692',
        x: 50,
        y: 26,
        width: 90,
        height: 14,
        fontFamily: 'Roboto Condensed, Arial',
        fontSize: 22,
        fontWeight: 900,
        color: '#ffbe0b',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 2
      },
      {
        id: 'train_name_hi',
        label: 'Train Name (Hindi)',
        defaultValue: 'बेंगलुरु ह. निज़ामुद्दीन राजधानी एक्सप्रेस',
        placeholder: 'राजधानी एक्सप्रेस',
        x: 50,
        y: 45,
        width: 92,
        height: 17,
        fontFamily: 'Nirmala UI, Arial',
        fontSize: 25,
        fontWeight: 700,
        color: '#ffffff',
        align: 'center'
      },
      {
        id: 'train_name_en',
        label: 'Train Name (English)',
        defaultValue: 'BENGALURU - NZM RAJDHANI EXP.',
        placeholder: 'RAJDHANI EXPRESS',
        x: 50,
        y: 64,
        width: 94,
        height: 16,
        fontFamily: 'Arial, Roboto Condensed',
        fontSize: 24,
        fontWeight: 900,
        color: '#ffffff',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1.5
      },
      {
        id: 'route_endpoints',
        label: 'Route / Via',
        defaultValue: 'VIA: DHONE · KACHEGUDA · NAGPUR · BHOPAL · AGRA CANTT',
        placeholder: 'VIA DETAILS',
        x: 50,
        y: 84,
        width: 94,
        height: 12,
        fontFamily: 'Roboto Condensed, Arial',
        fontSize: 15,
        fontWeight: 700,
        color: '#ffd166',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1
      }
    ],
    quickPresets: [
      {
        id: 'preset-rajdhani-mumbai',
        name: 'Mumbai Rajdhani',
        description: '12951 / 12952 MMCT < > NDLS Rajdhani Express',
        values: {
          train_number: '12951 / 12952',
          train_name_hi: 'मुम्बई राजधानी एक्सप्रेस',
          train_name_en: 'MUMBAI RAJDHANI EXPRESS',
          route_endpoints: 'VIA: SURAT · VADODARA · RATLAM · KOTA · MATHURA'
        }
      },
      {
        id: 'preset-rajdhani-bengaluru',
        name: 'Bengaluru Rajdhani',
        description: '22691 / 22692 SBC < > H. Nizamuddin Rajdhani Express',
        values: {
          train_number: '22691 / 22692',
          train_name_hi: 'बेंगलूरु राजधानी एक्सप्रेस',
          train_name_en: 'BENGALURU RAJDHANI EXPRESS',
          route_endpoints: 'VIA: DHONE · KACHEGUDA · NAGPUR · BHOPAL · AGRA CANTT'
        }
      },
      {
        id: 'preset-rajdhani-chennai',
        name: 'Chennai Rajdhani',
        description: '12433 / 12434 MAS < > H. Nizamuddin Rajdhani Express',
        values: {
          train_number: '12433 / 12434',
          train_name_hi: 'चेन्नै राजधानी एक्सप्रेस',
          train_name_en: 'CHENNAI RAJDHANI EXPRESS',
          route_endpoints: 'VIA: VIJAYAWADA · WARANGAL · BALHARSHAH · NAGPUR · BHOPAL · AGRA'
        }
      }
    ],
    published: true,
    createdAt: '2026-09-05T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
    author: 'System Admin'
  },

  // 6. SLR GUARD / LUGGAGE VAN BOARD
  {
    id: 'slr-guard-luggage-board',
    name: 'SLR Guard Brake & Luggage Van Board',
    category: 'SLR Board',
    description: 'Guard cabin, brake van, and parcel luggage compartment markings with red warning borders.',
    aspectRatio: '16:5',
    baseWidth: 1000,
    baseHeight: 310,
    backgroundColor: '#ffffff',
    backgroundType: 'solid',
    borderColor: '#d90429',
    borderWidth: 8,
    borderRadius: 6,
    innerBorder: true,
    innerBorderColor: '#d90429',
    innerBorderPadding: 6,
    showBolts: true,
    fixedGraphics: [
      {
        id: 'slr-badge-left',
        type: 'badge',
        content: 'GUARD',
        x: 15,
        y: 8,
        fontSize: 14,
        fontWeight: 900,
        color: '#d90429',
        align: 'center'
      },
      {
        id: 'slr-badge-right',
        type: 'badge',
        content: 'SLR',
        x: 85,
        y: 8,
        fontSize: 14,
        fontWeight: 900,
        color: '#d90429',
        align: 'center'
      }
    ],
    fields: [
      {
        id: 'slr_train_info',
        label: 'Train Number & Destination',
        defaultValue: '12627 KARNATAKA EXPRESS',
        placeholder: 'TRAIN INFO',
        x: 50,
        y: 28,
        width: 92,
        height: 18,
        fontFamily: 'Roboto Condensed, Impact, Arial',
        fontSize: 26,
        fontWeight: 900,
        color: '#111111',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 2
      },
      {
        id: 'luggage_capacity',
        label: 'Luggage Compartment Capacity',
        defaultValue: 'LUGGAGE COMPARTMENT · CAPACITY: 4.0 TONNES',
        placeholder: 'CAPACITY',
        x: 50,
        y: 52,
        width: 92,
        height: 16,
        fontFamily: 'Arial, sans-serif',
        fontSize: 20,
        fontWeight: 700,
        color: '#d90429',
        align: 'center',
        textTransform: 'uppercase',
        letterSpacing: 1.5
      },
      {
        id: 'guard_cabin_note',
        label: 'Brake Van / Guard Room Notice',
        defaultValue: 'GUARD BRAKE VAN · गार्ड ब्रेक वैन · अनधिकृत प्रवेश वर्जित',
        placeholder: 'NOTICE',
        x: 50,
        y: 78,
        width: 94,
        height: 14,
        fontFamily: 'Nirmala UI, Arial',
        fontSize: 18,
        fontWeight: 700,
        color: '#111111',
        align: 'center'
      }
    ],
    published: true,
    createdAt: '2026-09-08T00:00:00.000Z',
    updatedAt: '2026-09-14T00:00:00.000Z',
    author: 'System Admin'
  }
];

