import { AtlasTemplate } from './types';

// Master 4K Texture Template Definitions for ICF, LHB, and Digital LED Boards
export const TEMPLATES: AtlasTemplate[] = [
  {
    id: "icf_4096_atlas",
    name: "ICF Standard 4096 Master Atlas",
    category: "ICF",
    coachType: "ICF Coaches (Blue & Utkrisht)",
    description: "Complete 4096×4096 texture sheet for ICF coaches: classic bolted yellow board, SLR luggage end-wall with sliding door, ICF class plates, and depot stencils.",
    bgTheme: "icf_classic_blue",
    boardColor: "#fbc02d",
    boardBorderColor: "#0d2b5c",
    textColor: "#000000",
    accentColor: "#9c1d1e",
    width: 4096,
    height: 4096,
    isStandardMaster: true,
    hasScrews: true,
    hasZoneBadge: true,
    hasCoachClass: true,
    hasViaStrip: true,
    fontFamily: "'Inter', sans-serif",
    layout: "full_atlas",
    atlasType: "icf",
    defaultParts: {
      longBoard: { x: 128, y: 128, width: 3840, height: 720 },
      slrLuggage: { x: 128, y: 1000, width: 1800, height: 1450 },
      doorPlates: { x: 2080, y: 1000, width: 1888, height: 1450 },
      depotStencils: { x: 128, y: 2600, width: 3840, height: 1368 }
    }
  },
  {
    id: "lhb_4096_atlas",
    name: "LHB Standard 4096 Master Atlas",
    category: "LHB",
    coachType: "LHB Stainless Steel Coaches",
    description: "Complete 4096×4096 texture sheet for LHB coaches: Red & Silver corrugation livery, yellow metal destination board, EOG Power Car end wall, LHB class plates, and FIAT bogie stencils.",
    bgTheme: "lhb_red_silver",
    boardColor: "#f7b118",
    boardBorderColor: "#9c1d1e",
    textColor: "#111111",
    accentColor: "#9c1d1e",
    width: 4096,
    height: 4096,
    isStandardMaster: true,
    hasScrews: true,
    hasZoneBadge: true,
    hasCoachClass: true,
    hasViaStrip: true,
    fontFamily: "'Inter', sans-serif",
    layout: "full_atlas",
    atlasType: "lhb",
    defaultParts: {
      longBoard: { x: 128, y: 128, width: 3840, height: 720 },
      slrLuggage: { x: 128, y: 1000, width: 1800, height: 1450 },
      doorPlates: { x: 2080, y: 1000, width: 1888, height: 1450 },
      depotStencils: { x: 128, y: 2600, width: 3840, height: 1368 }
    }
  },
  {
    id: "digiboard_4096_atlas",
    name: "Digiboards (LED Matrix) 4096 Master Atlas",
    category: "Digiboards",
    coachType: "Vande Bharat, Tejas & LHB Smart Coaches",
    description: "Complete 4096×4096 electronic texture sheet: High-intensity Amber/Green LED destination matrix display, Digital Door PIDS displays, end indicators, and electronic depot matrices.",
    bgTheme: "digital_dark_housing",
    boardColor: "#05070a",
    boardBorderColor: "#1e293b",
    textColor: "#ffaa00",
    accentColor: "#00ff66",
    width: 4096,
    height: 4096,
    isStandardMaster: true,
    hasScrews: true,
    hasZoneBadge: false,
    hasCoachClass: true,
    hasViaStrip: false,
    fontFamily: "'VT323', monospace",
    layout: "full_atlas",
    atlasType: "digital",
    defaultParts: {
      longBoard: { x: 128, y: 128, width: 3840, height: 720 },
      slrLuggage: { x: 128, y: 1000, width: 1800, height: 1450 },
      doorPlates: { x: 2080, y: 1000, width: 1888, height: 1450 },
      depotStencils: { x: 128, y: 2600, width: 3840, height: 1368 }
    }
  },
  {
    id: "lhb_yellow_standard",
    name: "LHB Yellow Board (Single Strip)",
    category: "LHB",
    coachType: "LHB AC / Non-AC",
    description: "Single strip 3840×960 yellow destination board with LHB Red & Silver livery background.",
    bgTheme: "lhb_red_silver",
    boardColor: "#f7b118",
    boardBorderColor: "#9c1d1e",
    textColor: "#111111",
    accentColor: "#9c1d1e",
    width: 3840,
    height: 960,
    boardRect: { x: 320, y: 160, width: 3200, height: 640 },
    hasScrews: true,
    hasZoneBadge: true,
    hasCoachClass: true,
    hasViaStrip: true,
    fontFamily: "'Inter', sans-serif",
    layout: "three_tier"
  },
  {
    id: "icf_blue_standard",
    name: "ICF Classic Blue Board (Single Strip)",
    category: "ICF",
    coachType: "ICF Sleeper / General",
    description: "Single strip 3840×960 yellow metal sheet on blue ICF coach body with dark blue borders.",
    bgTheme: "icf_dark_blue",
    boardColor: "#fbc02d",
    boardBorderColor: "#0d2b5c",
    textColor: "#000000",
    accentColor: "#b71c1c",
    width: 3840,
    height: 960,
    boardRect: { x: 320, y: 160, width: 3200, height: 640 },
    hasScrews: true,
    hasZoneBadge: true,
    hasCoachClass: true,
    hasViaStrip: true,
    fontFamily: "'Inter', sans-serif",
    layout: "three_tier"
  },
  {
    id: "digital_led_amber",
    name: "Digital LED Board (Single Strip)",
    category: "Digiboards",
    coachType: "Modern LHB & Vande Bharat",
    description: "Single strip 3840×960 amber dot matrix LED display with realistic glow and LED pixel grid.",
    bgTheme: "digital_dark_housing",
    boardColor: "#05070a",
    boardBorderColor: "#1e293b",
    textColor: "#ffaa00",
    accentColor: "#ff7700",
    width: 3840,
    height: 960,
    boardRect: { x: 240, y: 160, width: 3360, height: 640 },
    hasScrews: true,
    hasZoneBadge: false,
    hasCoachClass: true,
    hasViaStrip: false,
    fontFamily: "'VT323', monospace",
    layout: "digital_matrix"
  }
];
