import { TrainData, RegionalLanguage } from './types';

// Offline Database of Popular Indian Railways Trains for Instant Auto-Fill
export const POPULAR_TRAINS: TrainData[] = [
  {
    trainNo: "12626",
    trainName: "Kerala Express",
    sourceEn: "NEW DELHI",
    sourceHi: "नई दिल्ली",
    sourceReg: "ന്യൂഡൽഹി",
    destEn: "THIRUVANANTHAPURAM CENTRAL",
    destHi: "तिरुवनंतपुरम सेंट्रल",
    destReg: "തിരുവനന്തപുരം സെൻട്രൽ",
    viaEn: "VIA: GWL, BPL, NGP, BZA, RU, ED, ERN",
    viaHi: "वाया: ग्वालियर, भोपाल, नागपुर, विजयवाड़ा, एर्नाकुलम",
    regLang: "Malayalam",
    zone: "SR",
    baseDepot: "TVC / SR",
    coachClass: "3A"
  },
  {
    trainNo: "12621",
    trainName: "Tamil Nadu Express",
    sourceEn: "MGR CHENNAI CENTRAL",
    sourceHi: "एम.जी.आर. चेन्नई सेंट्रल",
    sourceReg: "எம்.ஜி.ஆர் சென்னை சென்ட்ரல்",
    destEn: "NEW DELHI",
    destHi: "नई दिल्ली",
    destReg: "புது தில்லி",
    viaEn: "VIA: BZA, WL, NGP, BPL, GWL, AGC",
    viaHi: "वाया: विजयवाड़ा, वारंगल, नागपुर, भोपाल, आगरा",
    regLang: "Tamil",
    zone: "SR",
    baseDepot: "MAS / SR",
    coachClass: "SL"
  },
  {
    trainNo: "12951",
    trainName: "Mumbai Rajdhani Express",
    sourceEn: "MUMBAI CENTRAL",
    sourceHi: "मुंबई सेंट्रल",
    sourceReg: "मुंबई सेंट्रल",
    destEn: "NEW DELHI",
    destHi: "नई दिल्ली",
    destReg: "नवी दिल्ली",
    viaEn: "VIA: ST, BRC, RTM, KOTA",
    viaHi: "वाया: सूरत, वडोदरा, रतलाम, कोटा",
    regLang: "Marathi",
    zone: "WR",
    baseDepot: "MMCT / WR",
    coachClass: "2A"
  },
  {
    trainNo: "12301",
    trainName: "Howrah Rajdhani Express",
    sourceEn: "HOWRAH JN",
    sourceHi: "हावड़ा जं.",
    sourceReg: "হাওড়া জং",
    destEn: "NEW DELHI",
    destHi: "नई दिल्ली",
    destReg: "নতুন দিল্লি",
    viaEn: "VIA: ASN, DHN, GAYA, DDU, PRYJ, CNB",
    viaHi: "वाया: आसनसोल, धनबाद, गया, दीनदयाल उपाध्याय, कानपुर",
    regLang: "Bengali",
    zone: "ER",
    baseDepot: "HWH / ER",
    coachClass: "3A"
  },
  {
    trainNo: "12723",
    trainName: "Telangana Express",
    sourceEn: "HYDERABAD DECCAN",
    sourceHi: "हैदराबाद दक्कन",
    sourceReg: "హైదరాబాద్ డెక్కన్",
    destEn: "NEW DELHI",
    destHi: "नई दिल्ली",
    destReg: "న్యూ ఢిల్లీ",
    viaEn: "VIA: KZJ, RDM, BPA, NGP, BPL, GWL",
    viaHi: "वाया: काज़ीपेट, रामागुंडम, नागपुर, भोपाल",
    regLang: "Telugu",
    zone: "SCR",
    baseDepot: "HYB / SCR",
    coachClass: "3A"
  },
  {
    trainNo: "12617",
    trainName: "Mangala Lakshadweep Express",
    sourceEn: "ERNAKULAM JN",
    sourceHi: "एर्नाकुलम जं.",
    sourceReg: "എറണാകുളം ജം.",
    destEn: "H. NIZAMUDDIN",
    destHi: "ह. निज़ामुद्दीन",
    destReg: "ഹ. നിസാമുദ്ദീൻ",
    viaEn: "VIA: CLT, CAN, MAJN, MAO, PNVL, BSL, BPL",
    viaHi: "वाया: कोझिकोड, मडगांव, पनवेल, भुसावल, भोपाल",
    regLang: "Malayalam",
    zone: "SR",
    baseDepot: "ERS / SR",
    coachClass: "SL"
  },
  {
    trainNo: "12007",
    trainName: "Mysuru Shatabdi Express",
    sourceEn: "MGR CHENNAI CENTRAL",
    sourceHi: "एम.जी.आर. चेन्नई सेंट्रल",
    sourceReg: "ಕ್ರಾಂತಿವೀರ ಸಂಗೊಳ್ಳಿ ರಾಯಣ್ಣ ಬೆಂಗಳೂರು",
    destEn: "MYSURU JN",
    destHi: "मैसूरु जं.",
    destReg: "ಮೈಸೂರು ಜಂ.",
    viaEn: "VIA: KJM, SBC, MYA",
    viaHi: "वाया: कृष्णराजपुरम, बेंगलूरु, मांड्या",
    regLang: "Kannada",
    zone: "SWR",
    baseDepot: "MAS / SR",
    coachClass: "CC"
  },
  {
    trainNo: "12839",
    trainName: "Howrah - MGR Chennai Mail",
    sourceEn: "HOWRAH JN",
    sourceHi: "हावड़ा जं.",
    sourceReg: "হাওড়া জং",
    destEn: "MGR CHENNAI CENTRAL",
    destHi: "एम.जी.आर. चेन्नई सेंट्रल",
    destReg: "எம்.ஜி.ஆர் சென்னை சென்ட்ரல்",
    viaEn: "VIA: KGP, BBS, KUR, VSKP, BZA",
    viaHi: "वाया: खड़गपुर, भुवनेश्वर, विशाखापट्टनम, विजयवाड़ा",
    regLang: "Tamil",
    zone: "SER",
    baseDepot: "SRC / SER",
    coachClass: "SL"
  }
];

export const REGIONAL_LANGUAGES: RegionalLanguage[] = [
  { id: "None", name: "None (English & Hindi Only)" },
  { id: "Tamil", name: "Tamil (தமிழ்)" },
  { id: "Telugu", name: "Telugu (తెలుగు)" },
  { id: "Kannada", name: "Kannada (ಕನ್ನಡ)" },
  { id: "Malayalam", name: "Malayalam (മലയാളം)" },
  { id: "Bengali", name: "Bengali (বাংলা)" },
  { id: "Marathi", name: "Marathi (मराठी)" },
  { id: "Gujarati", name: "Gujarati (ગુજરાતી)" },
  { id: "Odia", name: "Odia (ଓଡ଼ିଆ)" },
  { id: "Punjabi", name: "Punjabi (ਪੰਜਾਬੀ)" }
];
